[package]
name = "htmeta-template"
version = "1.0.0"
edition = "2024"

[features]
default = []
test_gen = []

[dependencies]
htmeta = { path = "../htmeta" }
easy-ext = "1.0.2"
multimap.workspace = true


[dev-dependencies]
htmeta-auto-test = { path = "../htmeta-auto-test"}
