[package]
name = "htmeta-template"
version = "0.4.0"
edition = "2021"

[features]
default = []
test_gen = []

[dependencies]
htmeta = { path = "../htmeta" }
easy-ext = "1.0.2"


[dev-dependencies]
htmeta-auto-test = { path = "../htmeta-auto-test"}
